[allowlist]
  description = "Allowlisted files"
  [[allowlist.files]]
    path = ".gitleaks.toml"

######################
# GENERIC MATCH RULES
######################

[[rules]]
id = "generic-password"
description = "Detects generic password assignments"
regex = '''(?i)(password|passwd|pwd)[\s:=]+["']?[^"'\s]{8,}["']?'''
tags = ["password", "generic"]

[[rules]]
id = "generic-api-key"
description = "Detects API keys in various formats"
regex = '''(?i)\b(api[_-]?key|apikey|key)[\s:=]+["']?[A-Za-z0-9@!$%^&*()_+={}\[\]:;\"'<>,.?/\\|~-]{8,}["']?'''
tags = ["apikey", "generic", "key"]

[[rules]]
id = "generic-secret"
description = "Detects variables with the word 'secret'"
regex = '''(?i)(secret|secrets?[_-]?key)[\s:=]+["']?[A-Za-z0-9@!$%^&*()_+={}\[\]:;"'<>,.?/\\|~-]{8,}["']?'''
tags = ["secret", "generic"]

[[rules]]
id = "access-token"
description = "Generic access tokens"
regex = '''(?i)(access[_-]?token)["']?\s*[:=]\s*["']?[A-Za-z0-9\-._=]{16,}["']?'''
tags = ["token", "access"]

######################
# CLOUD PROVIDERS
######################

[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "key"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?(secret|access)[_-]?(key)?["']?\s*[:=]\s*["']?[A-Za-z0-9/+=]{40}["']?'''
tags = ["aws", "secret"]

[[rules]]
id = "gcp-secret-key-direct"
description = "Detects direct assignment of GCP secret key"
regex = '''(?i)gcp[-_]?secret[-_]?key\s*=\s*["'][^"']+["']'''
tags = ["gcp", "secret"]
files = ['*.js']

[[rules]]
id = "google-api-key"
description = "Google API Key"
regex = '''AIza[0-9A-Za-z\\-_]{35}'''
tags = ["gcp", "apikey"]

[[rules]]
id = "azure-client-secret"
description = "Azure Client Secret"
regex = '''(?i)(azure(.{0,20})?client(.{0,20})?secret)["']?\s*[:=]\s*["']?[a-z0-9._%+-]{10,}["']?'''
tags = ["azure", "client", "secret"]

######################
# 3RD PARTY SECRETS
######################

[[rules]]
id = "slack-token"
description = "Slack Token"
regex = '''xox[baprs]-[0-9a-zA-Z]{10,48}'''
tags = ["slack", "token"]

[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''gh[pousr]_[A-Za-z0-9_]{36,}'''
tags = ["github", "token"]

[[rules]]
id = "stripe-secret-key"
description = "Stripe Secret Key"
regex = '''sk_live_[0-9a-zA-Z]{24}'''
tags = ["stripe", "apikey"]

[[rules]]
id = "jwt"
description = "JWT token"
regex = '''eyJ[A-Za-z0-9-_=]+?\.[A-Za-z0-9-_=]+?\.[A-Za-z0-9-_.+/=]*'''
tags = ["jwt", "token"]

[[rules]]
id = "oauth-token"
description = "Generic OAuth Token"
regex = '''(?i)(oauth(_token)?|access_token)["']?\s*[:=]\s*["']?[a-z0-9]{32,}["']?'''
tags = ["oauth", "token"]

######################
# PRIVATE KEYS
######################

[[rules]]
id = "private-key"
description = "Private Key blocks"
regex = '''-----BEGIN(?: RSA)? PRIVATE KEY-----[\s\S]+?-----END(?: RSA)? PRIVATE KEY-----'''
tags = ["private", "key"]
