title = "Custom Gitleaks configuration"

[paths]
  exclude = [
    "./bookshelf/.gitleaks.toml"
    # Add any other paths or patterns to exclude here
  ]

[[rules]]
  id = "gcp-secret-key-direct"
  description = "Detects direct assignment of gcp-secret-key"
  regex = '''gcp-secret-key="[^"]*"'''
  tags = ["gcp", "secret", "direct-assignment"]
  files = ['*.js'] # Consider limiting to JavaScript files