# Define rules to detect common secrets

[[rules]]
  id = "gcp-access-key"
  description = "Detects GCP Access Key IDs"
  regex = '''AKIA[0-9A-Z]{16}'''
  tags = ["key", "gcp"]

# Define paths to exclude (common for Node.js projects)
[paths]
  exclude = [
    "*.txt/",
    "logs/",
    ".gitignore"
  ]

# Redact secrets in the output (recommended)
redact = true

# Example of allowing a specific false positive (use with caution!)
[allowlist]
  paths = [
    { path = "config/development.js", pattern = '"testApiKey": "thisisatestkey"' },
  ]

# Consider scanning the entire history for thoroughness
[options]
  scan_history = false