name: Docker Image Scan

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    paths:
      - bookshelf/**
      - .github/workflows/docker-scan.yaml

env:
  IMAGE_NAME: bookshelf-app

permissions:
  contents: read
  actions: read

jobs:
  Image-scan:
    name: 'Docker Image Scan'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Build Docker Image
      run: |
          docker build -t ${{env.IMAGE_NAME}} ./bookshelf
      
    - name: List Images
      run: |
          docker images
      
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{env.IMAGE_NAME}}
        args: --file=Dockerfile

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif