name: Docker Image Scan

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    paths:
      - bookshelf/**
      - .github/workflows/docker-scan.yaml

env:
  IMAGE_NAME: bookshelf-app

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  Image-scan:
    name: 'Docker Image Scan'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Build Docker Image
      run: |
          docker build -t ${{env.IMAGE_NAME}} ./bookshelf

    - name: Install snyk to html
      run: npm install snyk-to-html -g
        
    - name: Set up Snyk CLI
      uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk vulnerability scanner
      continue-on-error: true
      run: |
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk container test ${{env.IMAGE_NAME}} --file=./bookshelf/Dockerfile --project-name=Bookshelf-App --sarif-file-output=./snyk.sarif --severity-threshold=high --json | snyk-to-html -o bookshelf-scan.html

    - name: Run Trivy vulnerability scanner
      continue-on-error: true
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: '${{env.IMAGE_NAME}}'
        format: 'table'
        exit-code: '1'
        output: trivy-report.json
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Upload Report to GitHub Security Dashboard
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./snyk.sarif

    - name: Upload Report to Snyk Dashboard
      if: always()
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{env.IMAGE_NAME}}
        command: monitor
        args: "--project-name=Bookshelf-App --severity-threshold=high"

    - name: Upload Reports as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bookshelf-scan-report
        path: |
          ./bookshelf-scan.html
          ./trivy-report.json
    
    - name: Summarize Snyk Vulnerabilities
      if: always()
      run: |
        count=$(jq '[.runs[].results[] | select(.level == "error" or .level == "warning")] | length' snyk.sarif)
        echo "## Snyk Vulnerabilities: $count detected" >> $GITHUB_STEP_SUMMARY

    - name: Summarize Trivy Vulnerabilities
      if: always()
      run: |
        count=$(grep -E 'HIGH|CRITICAL' trivy-report.json | wc -l)
        echo "## Trivy Vulnerabilities: $count detected" >> $GITHUB_STEP_SUMMARY

