name: Docker Image Scan

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    paths:
      - bookshelf/**
      - .github/workflows/docker-scan.yaml

permissions:
  contents: read
  actions: read
