name: Docker Image Scan

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    paths:
      - bookshelf/**
      - .github/workflows/docker-scan.yaml

env:
  IMAGE_NAME: bookshelf-app

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  Image-scan:
    name: 'Docker Image Scan'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Build Docker Image
      run: |
          docker build -t ${{env.IMAGE_NAME}} ./bookshelf
      
    - name: List Images
      run: |
          docker images
      
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{env.IMAGE_NAME}}
        args: |
          --file=./bookshelf/Dockerfile
          --project-name=Bookshelf-App
          --sarif-file-output=snyk.sarif
          --report
          --output=./bookshelf-scan.html

    - name: Upload the SARIF file to GitHub Security Dashboard
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./bookshelf/snyk.sarif

    - name: Run Snyk Monitor
      if: always()
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{env.IMAGE_NAME}}
        command: monitor
        args: |
            --project-name=Bookshelf-App

    - name: Upload HTML Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bookshelf-scan-report
        path: ./bookshelf-scan.html