name: gitleaks
on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - bookshelf/**
      - .github/workflows/gitleaks.yaml

jobs:
  Secrets-check:
    name: Secret Check
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/bookshelf

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install gitleaks 
      run: |
        sudo apt install gitleaks

    - name: Find Secrets using GitLeaks
      run: gitleaks detect --source . -v