name: Snyk Security Scan

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    paths:
      - bookshelf/**
      - .github/workflows/snyk-scan.yaml

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security:
    name: 'Snyk Scan'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/bookshelf
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - run: |
          ls -al 
          pwd

    - name: Set up Node.js
      uses: actions/setup-node@v3

    - name: Install Dependencies
      run: npm install
      working-directory: ./bookshelf

    # - name: Snyk to check for vulnerabilities
    #   uses: snyk/actions/node@master
    #   continue-on-error: true
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   with:
    #     command: test
    #     args: "--all-projects --exclude=build.gradle --json-file-output=./bookshelf/snyk.json"

    - run: |
          ls -al 
          pwd

    # - name: Snyk to check for vulnerabilities
    #   uses: snyk/actions/node@master
    #   continue-on-error: true
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   with:
    #     command: test
    #     args: "--all-projects --exclude=build.gradle --sarif-file-output=./bookshelf/snyk.sarif"


## Testing SBOM, It requires premium package
    - name: Install snyk to html
      run: npm install snyk-to-html -g
        
    - name: Set up Snyk CLI
      uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Snyk vulnerability Check
      continue-on-error: true
      run: |
        pwd
        ls -al
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk test --project-name=Bookshelf-Code --exclude=build.gradle --sarif-file-output=./snyk.sarif --severity-threshold=high --json | snyk-to-html -o bookshelf-scan.html

    - name: Snyk SBOM Check
      continue-on-error: true
      run: |
        pwd
        ls -al
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk sbom --format=cyclonedx1.6+json --project-name=Bookshelf-Code --json-file-output=sbom-report.json
        snyk sbom monitor --format=cyclonedx1.6+json --project-name=Bookshelf-Code

    - name: Snyk Monitor
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
        args: "--all-projects --exclude=build.gradle"

    - name: Upload Snyk JSON as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: snyk-security-report
        path: |
          ./bookshelf-scan.html
          ./sbom-report.json


    - name: Upload the SARIF file to GitHub Security Dashboard
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./bookshelf/snyk.sarif