name: Snyk Security Scan

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    paths:
      - bookshelf/**
      - .github/workflows/snyk-scan.yaml

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./bookshelf

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: "--all-projects --exclude=build.gradle --json-file-output=./bookshelf/snyk.json"

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: "--all-projects --exclude=build.gradle --sarif-file-output=./bookshelf/snyk.sarif"

      - name: Run Snyk Monitor
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: "--all-projects --exclude=build.gradle"

      - run: |
              ls -al  
              cd bookshelf
              ls -al 

      - name: Upload Snyk JSON as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-security-report
          path: ./bookshelf/snyk.json

      - name: Upload the SARIF file to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./bookshelf/snyk.sarif
        env:
           GITHUB_TOKEN: ${{ secrets.SECURITY_TOKEN }}




# name: Snyk Security Scan

# on:
#   workflow_dispatch:
#   pull_request:
#     types: [opened, reopened, synchronize]
#   push:
#     branches:
#       - main
#     paths:
#       - bookshelf/**
#       - .github/workflows/snyk-scan.yaml

# jobs:
#   security:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3

#       - name: Install Dependencies
#         run: npm install
#         working-directory: ./bookshelf

#       - name: Run Snyk to check for vulnerabilities
#         uses: snyk/actions/node@master
#         continue-on-error: true
#         env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#         with:
#           command: test
#           # args: "--all-projects --exclude=build.gradle --sarif-file-output=snyk.sarif"
#           args: "--all-projects --exclude=build.gradle --json-file-output=./snyk.json"

#       - run: |
#               ls -al  
#               cd bookshelf
#               ls -al 
          
#       - name: Run Snyk Monitor (Long-term Monitoring)
#         uses: snyk/actions/node@master
#         env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#         with:
#           command: monitor
#           args: "--all-projects --exclude=build.gradle"

#       - name: Publish Snyk Report as Artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: snyk-security-report
#           path: ./snyk.json

#       # - uses: garethr/snyk-to-sarif@master
#       - name: Install Snyk to SARIF Converter
#         run: npm install -g snyk-to-sarif
        
#       - uses: actions/upload-artifact@v4
#         with:
#           name: SARIF
#           path: ./snyk.sarif

#       - run: |
#               ls -al  
#               cd bookshelf
#               ls -al  
          
#       - name: Upload the SARIF file
#         uses: github/codeql-action/upload-sarif@v3
#         with:
#           sarif_file: snyk.sarif

#       # - run: |
#       #         ls -al  
#       #         cd bookshelf
#       #         ls -al  

#       # - name: Install Snyk to SARIF Converter
#       #   run: npm install -g snyk-to-sarif

#       # - name: Convert Snyk JSON to SARIF
#       #   run: snyk-to-sarif ./bookshelf/snyk-report.json -o ./bookshelf/snyk-results.sarif

#       # - run: |
#       #        ls -al  
#       #        cd bookshelf
#       #        ls -al  

#       # - name: Publish Snyk Report to GitHub Security Dashboard
#       #   uses: github/codeql-action/upload-sarif@v3
#       #   with:
#       #     sarif_file: ./bookshelf/snyk-results.sarif
