name: Snyk Security Scan

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    paths:
      - bookshelf/**
      - .github/workflows/snyk-scan.yaml

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./bookshelf

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: "--all-projects --exclude=build.gradle --sarif-file-output=./bookshelf/snyk.sarif"

      - name: Install SARIF to HTML Converter
        run: npm install -g @microsoft/sarif-multitool

      - name: Convert Snyk SARIF to HTML
        run: sarif multitool transform --output ./bookshelf/snyk.html ./bookshelf/snyk.sarif

      - name: Upload Snyk HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-security-report
          path: ./bookshelf/snyk.html

      - name: Upload Snyk Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-security-report
          path: ./bookshelf/snyk.html

      - name: Snyk Job Summary
        if: always()
        run: |
          if [ -s bookshelf/snyk.json ]; then
            echo "### 🛑 Snyk detected vulnerabilities 🛑" >> $GITHUB_STEP_SUMMARY
            echo "| Package | Severity | Issue | Path |" >> $GITHUB_STEP_SUMMARY
            echo "|---------|----------|-------|------|" >> $GITHUB_STEP_SUMMARY
            jq -r '.vulnerabilities[] | 
              "| \(.package // "N/A") | \(.severity // "N/A") | \(.title // "N/A") | \(.from | join(" > ") // "N/A") |"' bookshelf/snyk.html >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ No vulnerabilities detected by Snyk." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Run Snyk Monitor
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: "--all-projects --exclude=build.gradle"

      - name: Upload the SARIF file to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./bookshelf/snyk.sarif
