name: DAST Zap Scan

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    paths:
      - .github/workflows/zap-scan.yaml

env:
  INSTANCE_IP: 127.0.0.1

permissions:
  contents: read
  security-events: write
  actions: read

jobs:

  zap-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/juice-shop

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t juice-shop .

    - name: List Docker Image
      run: docker images 

    - name: Start Juice Shop App
      run: |
        docker run -d -p 3000:3000 juice-shop 

    - name: Wait for Juice Shop to be Ready
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:3000 >/dev/null; then
            echo "Juice Shop is up!"
            break
          fi
          echo "Waiting for Juice Shop..."
          sleep 5
        done

    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
        target: "http://localhost:3000"
        allow_issue_writing: false

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap_report.html
        path: report_html.html
